# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: R CMD check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
    paths:
      - man/**
      - R/**
      - tests/**
      - DESCRIPTION
      - NAMESPACE
      - .github/workflows/R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    
    timeout-minutes: 15
    
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,     r: 'devel'}
          - {os: macos-latest,     r: 'release'}
          - {os: macos-latest,     r: 'oldrel-1'}
          - {os: macos-latest,     r: '4.1'}
          - {os: macos-14,         r: 'release'}
          
          - {os: windows-latest,   r: 'devel'}
          - {os: windows-latest,   r: 'release'}
          - {os: windows-latest,   r: 'oldrel-1'}
          - {os: windows-latest,   r: '4.1'}
          - {os: windows-2022,     r: 'release'}
          
          - {os: ubuntu-latest,    r: 'devel' }
          - {os: ubuntu-latest,    r: 'release'}
          - {os: ubuntu-latest,    r: 'oldrel-1'}
          - {os: ubuntu-latest,    r: '4.1'}
          - {os: ubuntu-22.04,     r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NOT_CRAN: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install system font deps (macOS)
        if: runner.os == 'macOS'
        run: brew install freetype libpng
        
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

      - name: Show install log
        if: always()
        run: find . -name '00install.out' -exec cat {} +
        shell: bash
